name: xcube-gedidb
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - python>=3.10
  - xarray
  - xcube
  - pip
  - pip:
      - gedidb
  # for testing
  - black
  - flake8
  - pytest
  - pytest-cov
  - pytest-recording
